### ISSUE TITLE
Can't get this code to work...

### ISSUE THREAD

**Issue by htartisan** [agilityfeat/webrtc-video-conference-tutorial#6]
I have downloaded this code, and tried it on a computer with Kurento server, but it doesn't seem to work.  The browser client that is created will create a "room" and open the webcam, but the browser client never receives any WebRTC streams from other browser clients.

Any suggestions on how to get it to work?

Does it  require a specific version of Kurento, or any other software to be installed?

**Comment by nuxero** [comment]
Are you getting errors either on the browser or the terminal? Also take a look at this [post](https://webrtc.ventures/2018/08/tutorial-%e2%80%8bhow-%e2%80%8bto-%e2%80%8bbuild-%e2%80%8ba-%e2%80%8bvideo-conference-%e2%80%8bapplication-%e2%80%8bwith-webrtc-%e2%80%8b-%e2%80%8bkurento-%e2%80%8bmedia-%e2%80%8bserver/) which is the one where this branch is used

**Comment by kanhaiya-2000** [comment]
@nuxero  Yes,i too get the same kind of problem.The error i faced is {data:{type:"ICE_ADD_CANDIDATE_ERROR"},code:40401}
My node version is 12.16.1
npm version is 6.14.7
Any suggestions on how to get rid of this error?

The complete log is

Trace: Error: Error adding candidate
    at /home/kanhaiya/Videos/complaintlodger/node_modules/kurento-client/lib/KurentoClient.js:362:24
    at Object.dispatchCallback [as callback] (/home/kanhaiya/Videos/complaintlodger/node_modules/kurento-jsonrpc/lib/index.js:613:9)
    at processResponse (/home/kanhaiya/Videos/complaintlodger/node_modules/kurento-jsonrpc/lib/index.js:744:15)
    at RpcBuilder.decode (/home/kanhaiya/Videos/complaintlodger/node_modules/kurento-jsonrpc/lib/index.js:805:5)
    at Stream.transportMessage (/home/kanhaiya/Videos/complaintlodger/node_modules/kurento-jsonrpc/lib/index.js:225:10)
    at Stream.emit (events.js:311:20)
    at Stream.EventEmitter.emit (domain.js:482:12)
    at drain (/home/kanhaiya/Videos/complaintlodger/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/kanhaiya/Videos/complaintlodger/node_modules/through/index.js:45:5)
    at WebsocketStream.onMessage (/home/kanhaiya/Videos/complaintlodger/node_modules/websocket-stream/index.js:45:15)
    at WebSocket.onMessage (/home/kanhaiya/Videos/complaintlodger/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:355:18)
    at WebSocket.emit (events.js:311:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at Receiver.self._receiver.ontext (/home/kanhaiya/Videos/complaintlodger/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:682:10)
    at Receiver.finish (/home/kanhaiya/Videos/complaintlodger/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:391:14)
    at Receiver.expectHandler (/home/kanhaiya/Videos/complaintlodger/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:378:31) {
  code: 40401,
  data: { type: 'ICE_ADD_CANDIDATE_ERROR' }
}
    at WebRtcEndpoint.noop (/home/kanhaiya/Videos/complaintlodger/node_modules/kurento-client-elements/lib/WebRtcEndpoint.js:35:22)
    at callback2 (/home/kanhaiya/Videos/complaintlodger/node_modules/promisecallback/index.js:27:25)
    at tryCatch (/home/kanhaiya/Videos/complaintlodger/node_modules/es6-promise/dist/es6-promise.js:410:12)
    at invokeCallback (/home/kanhaiya/Videos/complaintlodger/node_modules/es6-promise/dist/es6-promise.js:425:13)
    at publish (/home/kanhaiya/Videos/complaintlodger/node_modules/es6-promise/dist/es6-promise.js:393:7)
    at publishRejection (/home/kanhaiya/Videos/complaintlodger/node_modules/es6-promise/dist/es6-promise.js:335:3)
    at flush (/home/kanhaiya/Videos/complaintlodger/node_modules/es6-promise/dist/es6-promise.js:121:5)
at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by kanhaiya-2000** [comment]
@nuxero  I solved this problem by installing the latest version of KMS using docker.
